### ISSUE TITLE
Italian Dubs shown as English

### ISSUE THREAD

**Issue by marcostudios** [Dragicafit/Crunchyroll-With-Better-Seasons#12]
Recently Crunchyroll released Italian dubs, but on the extension it shows as English.

![immagine](https://user-images.githubusercontent.com/5209299/179844396-a5d99256-3c41-474e-93c9-246a90e2d14d.png)

**Comment by Dragicafit** [comment]
Thank you for this report, I almost finished to work on it, Crunchyroll also changed the way subs are handled, I will fix this in the same mr.
