### ISSUE TITLE
Crunchyroll With Better Seasons don't work

### ISSUE THREAD

**Issue by xdyosh** [Dragicafit/Crunchyroll-With-Better-Seasons#15]
Hi I'm the guy who commented on the Chrome Web Store that the extension did not work, I answer here because I think it will be faster. In general it does not work for me on any page, I do not understand why. Try both Edge and Opera GX.

Take screenshots on some Crunchyroll pages: https://imgur.com/gallery/Zu7g3zf

**Comment by Dragicafit** [comment]
I tried everything to replicate your problem but I can't.
I installed it in Edge, tried in Spanish but it works.
![Screenshot_20220815_164339](https://user-images.githubusercontent.com/43404588/184657981-0d8576aa-1739-4747-87f2-c495a320a55b.png)
Maybe Crunchyroll is releasing a new version of beta for selected users.
In which country do you live ?

**Comment by xdyosh** [comment]
I'm from Mexico. I also tried using VPN and using another account I had but nothing, it's weird. Perhaps and as you say, something changed Crunchyroll

**Comment by Matth7878** [comment]
Just to comment that I have the same problem.
I live in France but use Crunchyroll with english language. Tried with my native language but it's the same.
For Ao Ashi I still have the drop down menu with all available languages :-/

**Comment by Dragicafit** [comment]
I finally had the same problem, can you check the last version (0.5.1, you should have it with auto update) to see if it fixes your problem?

**Comment by Matth7878** [comment]
Working now with 0.51 ! Thanks ! :-)

**Comment by xdyosh** [comment]
It also works for me again with 0.51 thank you c:
![crunchyroll](https://user-images.githubusercontent.com/111243523/187050151-ba04e0d8-0ef3-44fa-a73b-4fa573e53cf1.png)
