### ISSUE TITLE
Audio selection on player not working on Google Chrome

### ISSUE THREAD

**Issue by Symptomaker** [Dragicafit/Crunchyroll-With-Better-Seasons#16]
Hey!
Not sure why, but the audio option is no longer available inside the player, even though the extension works just fine on the shows pages
![Captura de tela 2022-08-20 011150](https://user-images.githubusercontent.com/111624277/185728505-892a67ce-2298-4270-b9ca-d0d03b082363.png)
![Captura de tela 2022-08-20 011209](https://user-images.githubusercontent.com/111624277/185728507-29d542a1-5dac-45d2-b7a8-f6753aca4903.png)
.

**Comment by Dragicafit** [comment]
Do you still have the problem?
