### ISSUE TITLE
Hotkey to toggle subtitles

### ISSUE THREAD

**Issue by Gnothenat-The-Wizard** [Dragicafit/Crunchyroll-With-Better-Seasons#17]
A hotkey to toggle the subtitles on and off would be really helpfull as a lot of the dubs lack subtitles for text on screen so an easy way to turn them on and off would be really helpful

**Comment by Dragicafit** [comment]
I was working on this but I discovered that there is already a hotkey for that: "C".

Does this do what you want ?

**Comment by Gnothenat-The-Wizard** [comment]
Yeah thanks I couldn't find it listed anywhere so assumed there was not one
