### ISSUE TITLE
Doesnt work since Beta.Crunchyroll.com became Crunchyroll.com

### ISSUE THREAD

**Issue by Phoenomenal** [Dragicafit/Crunchyroll-With-Better-Seasons#18]
Hello! 

Extension doesnt work  since Beta.Crunchyroll.com  cease to exist and  redirect to new Crunchyroll.com site with new interface formerly Beta.

**Comment by Dragicafit** [comment]
Thanks a lot, didn't see this one coming.

Fixed in 0.6.1
