### ISSUE TITLE
The subs on dubs feature is not working

### ISSUE THREAD

**Issue by kevinization** [Dragicafit/Crunchyroll-With-Better-Seasons#23]
I've been using your Crunchyroll with better seasons's extension for a long time, but today I noticed that it doesn't work anymore, particularly the subs on dubs feature. Do you know what's happening and how to fix it? The list of subs in dubbed anime is not appearing anymore. I tried it in Brave and Firefox.

The following image shows that the list is not appearing. Dub language: Spanish (Latinamerica),
![image](https://github.com/user-attachments/assets/2212348f-bd02-4ab0-8a44-5046a98137c1)

**Comment by Dragicafit** [comment]
Thank you for reporting this issue, a fix has been sent in the release v0.7.6
